Sync respec contents with TS typings
rdfjs/query-spec pull request #11
Opened 2022-02-25 15:55 UTC by rubensworks

This PR brings the respec document up-to-date with what we defined in [`queryable-spec.ts`](https://github.com/rdfjs/query-spec/blob/master/queryable-spec.ts) (which I guess can be removed after this?). This makes everything more human-readable.

2022-02-25 19:16 UTC, jacoscaz commented
That was fast! And good!

2022-02-25 19:30 UTC, jacoscaz requested changes
Nice work! The only thing that I _think_ is missing is more internal linking between uses and definitions, although I'm very new to WebIDL and I need to do a bit of learning myself as to the extent to which this is supported. Other than that, just some minor nitpicks.

2022-02-25 19:30 UTC, jacoscaz commented on index.html
> +      <dfn>resultType</dfn> represents the type of query that is being executed.
This might create confusion. Result type represents.. the result type of the query that is being executed. It does not represent the query type (e.g. `CONSTRUCT` and `DESCRIBE` are two different types of queries but lead to the same result type).

2022-02-25 19:30 UTC, jacoscaz commented on index.html
> +      <dfn>execute()</dfn> asynchronously returns the a stream of <code>Bindings</code>.
minor grammar issue: "the a"

2022-02-25 19:30 UTC, jacoscaz commented on index.html
> +      <dfn>metadata()</dfn> asynchronously returns the a <code>QueryMetadata</code> object.
minor grammar issue: "the a"

2022-02-25 19:30 UTC, jacoscaz commented on index.html
> +      Promise&lt;QueryMetadata&lt;Bindings&gt;&gt; metadata(QueryMetadataOptions? options);
Is there no way to make `QueryMetadataOptions` actionable, so that clicking upon it brings you to its definition? Either here or at line 275. Same applies for `QueryExecuteOptions`.

2022-02-28 09:26 UTC, rubensworks commented
Thanks for the feedback @jacoscaz, all comments should be resolved now.

2022-02-28 09:28 UTC, rubensworks commented
@gsvarovsky, once this PR is merged, feel free to open a new PR to add yourself as author to this spec.

2022-02-28 10:43 UTC, jacoscaz approved these changes

2022-02-28 10:48 UTC, merged